/**
 * 错误码常量(前后端共享)
 *
 * 命名规范:UPPER_SNAKE_CASE,语义对齐 HTTP 错误模式。
 */

export const ERROR_CODES = {
  // 鉴权
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_EXISTS: 'EMAIL_EXISTS',
  UNAUTHORIZED: 'UNAUTHORIZED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',

  // 资源
  CONVERSATION_NOT_FOUND: 'CONVERSATION_NOT_FOUND',
  MESSAGE_NOT_FOUND: 'MESSAGE_NOT_FOUND',
  STREAM_NOT_FOUND: 'STREAM_NOT_FOUND',
  ATTEMPT_NOT_FOUND: 'ATTEMPT_NOT_FOUND',
  SCENE_NOT_FOUND: 'SCENE_NOT_FOUND',
  NOT_FOUND: 'NOT_FOUND',

  // 状态机 / 学习流
  STATE_TRANSITION_DENIED: 'STATE_TRANSITION_DENIED',
  CONVERSATION_LOCKED: 'CONVERSATION_LOCKED',

  // 校验
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  WIDGET_VALIDATION_FAILED: 'WIDGET_VALIDATION_FAILED',

  // Skill / AI
  SKILL_NOT_FOUND: 'SKILL_NOT_FOUND',
  SKILL_NOT_ALLOWED: 'SKILL_NOT_ALLOWED',
  PROVIDER_ERROR: 'PROVIDER_ERROR',
  ROUTER_FALLBACK: 'ROUTER_FALLBACK',

  // 兜底
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
